language: php

php:
  - 7.1

services:
  - mysql
  - redis-server

before_script:
  - cp .env.travis .env
  - mysql -e 'create database keychest;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - 'sed -i "s/->json/->text/g" ./vendor/acacha/laravel-social/database/migrations/*.php'
  - npm install
  - npm run dev

script:
  - vendor/bin/phpunit || (cat ./storage/logs/laravel.log; exit 1)

cache:
  directories:
    - node_modules
    - vendor

